"""Add new columns or modify existing ones

Revision ID: bb91861ffc43
Revises: 76e6e292ab67
Create Date: 2024-11-15 14:56:48.705267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb91861ffc43'
down_revision: Union[str, None] = '76e6e292ab67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_sessions', sa.Column('current_question_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_sessions', 'current_question_index')
    # ### end Alembic commands ###
